### ISSUE TITLE
Sign into Instagram problematic

### ISSUE THREAD

**Issue by anoduck** [AppleGamer22/scr-web#2]
I may be jumping the gun a little too soon, the repo is after all still an alpha. But, wanted to try it out since I am interested in all things social engineering. Was not able to authenticate with Instagram and received the following error. 

```
Http failure response for http://localhost:4100/api/auth/sign_in/instagram: 0 Unknown Error
```

Is there something that I missed or failed to do.

**Comment by AppleGamer22** [comment]
Thanks for submitting this issue.
Are you running a MongoDB instance on you local machine? The Docker container is currently set in a way that it can only connect to a locally run MongoDB instance.
If not, perhaps:
1. Create this docker-compose.yml configuration:
```yml
version: "3"
services:
scr:
  container_name: scr
  image: applegamer22/scr-web:<version>
  environment:
  JWT_SECRET: some_private_key
  ports:
    - 4100:4100
    - 4200:4200
    - 7777:7777
  volumes:
    - ./some_local_directory:/scr/users
database:
  container_name: database
  image: mongo:4.2.0
  restart: always
  volumes:
    - ./database:/data/db
  ports:
    - 27017:27017
```
2. Run `docker-compose up --build` in your command prompt.
  * I will update the getting started documentation in order to make it more clear.

If your Docker setup contains the above mentioned docker-compose.yml file, could you please provide more details on how you run this Docker container.

**Comment by anoduck** [comment]
WOW RESULT! I probably should have delved further into the code and realized the need for mongodb myself, and I apologize for not doing so. I was already using docker-compose to run the container, so I will modify the file and this should resolve the issue. Thanks!

**Comment by anoduck** [comment]
I was a little premature closing out the issue. I had the exact same docker-compose and was receiving the issue, I was only behind by one release. Trying to run it again after removing some quotation marks from the JWT secret.

**Comment by AppleGamer22** [comment]
1. Have you signed up with Instagram credentials using the web interface and successfully verified the existence of a new document in the users collection?
  * This will allow the server-side application to stop someone trying to use your credentials and browser instance.
2. Have you successfully signed-in using the web interface?
  * This will try to log-in to instagram with your credentials on your behalf through a chromium based automation.
3. Have you tried to get the url of a post picture/video?

The server log from docker-compose might tell you more about the issue.

**Comment by anoduck** [comment]
You might have to inform me of a means to generate more debugging information. Because there appears to be nothing out of the ordinary in the docker logs. 

The exact issue is that I open the web interface, attempt to login, and receive this obscure error message:

```
Http failure response for http://localhost:4100/api/auth/sign_up/instagram: 0 Unknown Error
```

Which does not appear to be helpful. The only thing that I can think of is that `localhost`  might be some hint that the app is not listening on `0.0.0.0:4100` but rather `127.0.0.1:4100` and is blocking connections to that port from the local network `192.168.1.1:4100`.  Because you can access the web interface, but when you connect via `:4200` you recieve `"Cannot GET /"`. Which tells me it is looking for something that is not available.

**Comment by AppleGamer22** [comment]
After running `docker-compose up` in the command prompt, something like the following log should appear:  ![Screenshot_20200525_120036](https://user-images.githubusercontent.com/22742927/82771464-82294780-9e7f-11ea-840f-67d22a9b2d8e.jpeg)
The green colored log text should say that the server successfully connected to MongoDB at and that the server successfully started.
The client side application explicitly logs that it listens on `http://127.0.0.1:4200/`, and the server side application listens on `http://localhost:4100/api`. Perhaps on your OS settings, `localhost` is specified as a different IP address than what the Alpine Linux container the apps runs on. I might suggest to make sure that localhost points to the standard `http://127.0.0.1`. Regardless, I am going to try to implement an option to specify hosting address as an environment variable in `docker-compose.yml`.

**Comment by anoduck** [comment]
### Check this out, here is terminal output from running the container.  
[![asciicast](https://asciinema.org/a/nBsV63b8htXKv6O7XqEYw620r.svg)](https://asciinema.org/a/nBsV63b8htXKv6O7XqEYw620r)

### Here is the response I recieved from the web browser.  
![Screenshot_2020-05-25 scr io](https://user-images.githubusercontent.com/9925396/82782716-01406080-9e2b-11ea-826f-45162f6f0911.png)

**Comment by anoduck** [comment]
I think I found the problem. For some reason or another, now, when using docker-compose a new bridged network is created instead of using the default `docker0`. I was assuming that `docker0` would be used, as it had in the past. For another unknown reason, I was permitted to connect to the container.

**Comment by AppleGamer22** [comment]
After some reading in the [Docker documentation](https://docs.docker.com/config/containers/container-networking/#published-ports), i found that you can map both ports and ip address. If you want the server side port 4100 to be routed to 0.0.0.0, you can insert that address before the port specification as shown below:
```yml
version: "3"
services:
  scr-web:
    container_name: scr-web
    image: applegamer22/scr-web:<version>
    environment:
      JWT_SECRET: <some_private_key>
    ports:
      - <ip_address>:4100:4100
      - 4200:4200
      - 7777:7777
    volumes:
      - ./some_local_directory:/scr/users
  database:
    container_name: database
    image: mongo:4.2.3
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
```

**Comment by anoduck** [comment]
No change. 

I am getting more concerned with the response on port 4100 than the inability to sign up for instagram. 

Going to try to run outside of docker on kali, and then get a friend to help me troubleshoot the javascript better. Not necessarily in that order.

**Comment by BullShark** [comment]
> 
> @BullShark help me please, brother...

Try running his other project scr-cli. See if that works.

**Comment by AppleGamer22** [comment]
In the latest alpha release, both the server and client are running from one port.
```yml
version: "3"
services:
 scr:
   container_name: scr
   image: applegamer22/scr-web:<version>
   environment:
   JWT_SECRET: <some_private_key>
   ports:
     - <some_available_port>:4100
   volumes:
     - ./some_local_directory:/scr/users
 database:
   container_name: database
   image: mongo:4.2.0
   restart: always
   volumes:
     - ./database:/data/db
   ports:
     - 27017:27017
```
If port 4100 is still not responding on your host machine, can you try routing the traffic to a different port on your host machine to port 4100 on the container?
